version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: mypod
      POSTGRES_PASSWORD: "2qBi9o2Bhvv7U3YgeN1dItQpxL1izTBR"
    volumes:
      - mypod_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "SBdqPtXy10fZqvfsk-28YgT8VqGktiXk"
    environment:
      - REDIS_REPLICATION_MODE=master
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
volumes:
  mypod_data:
